modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="aalc"
version="1.0.0"
displayName="aalc"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="PC, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.aalc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



